target("VulkanTest")
    set_kind("binary")
    add_files("main.cpp")
    before_build_file(enable_clang_tidy)
    on_load(function (target)
            target:add(find_packages("vulkan", "sdl2"))
    end)
