target("VulkanTriangle")
    set_kind("binary")
    add_rules("glsl")
    add_deps("VulkanBase")
    add_files("main.vert", "main.frag")
    add_files("main.cpp", "triangle.cpp")
    add_includedirs(path.join("$(projectdir)", "include"))
    on_load(function (target)
            target:add(find_packages("vulkan", "sdl2"))
    end)
